[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sartorius"
version = "0.6.0"
description="Python driver for Sartorius and Minebea Intec scales."
license = "GPL-2.0-or-later"
dependencies = [
  "pyserial",
]
authors = [
  {name = "Pat Fuller", email = "patrickfuller@gmail.com" },
]
maintainers = [
  {name = "Alex Ruddick", email = "alex@ruddick.tech" }
]
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Human Machine Interfaces",
    "Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)"
]

[dependency-groups]
dev = [
  "mypy>=1.18.2",
  "pytest",
  "pytest-cov",
  "pytest-asyncio",
  "ruff==0.13.3",
  "types-pyserial",
]

[project.scripts]
sartorius = "sartorius:command_line"

[project.urls]
Homepage = "https://github.com/alexrudd2/sartorius/"
Issues = "https://github.com/alexrudd2/sartorius/issues"

[tool.setuptools.package-data]
"sartorius" = ["py.typed"]

[tool.ruff]
extend-exclude = ["venv*"]
line-length = 99
target-version = "py310"

[tool.ruff.lint]
ignore = [
  "D104",     # Missing docstring in public package
]
select = [
    "B",   # flake8-bugbear
    "C",   # complexity
    "COM", # trailing commas
    "D",   # docstrings
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "PT",  # flake8-pytest
    "RUF", # ruff base config
    "SIM", # flake-simplify
    "UP",  # pyupgrade
    "W",   # pycodestyle warnings
    "YTT", # flake8-2020
    "ARG", # flake8-unused args
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.flake8-unused-arguments]
ignore-variadic-names = true

[tool.mypy]
check_untyped_defs = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs = false

[tool.pytest.ini_options]
addopts = "--cov=sartorius"
asyncio_mode = "auto"

[tool.pyright]
venvPath = "."
venv = ".venv"
